import React, { useState, useEffect } from 'react';
import { ConversionResult } from '../types';
import { formatBytes } from '../utils/imageUtils';
import {
  Download,
  ExternalLink,
  CheckCircle2,
  FileText,
  Clock,
  HardDrive,
  Cpu,
  ChevronDown,
  ChevronUp,
  X,
  Share2,
} from 'lucide-react';

interface PdfPreviewProps {
  result: ConversionResult;
  onClose: () => void;
}

export const PdfPreview: React.FC<PdfPreviewProps> = ({ result, onClose }) => {
  const [blobUrl, setBlobUrl] = useState<string>('');
  const [showLogs, setShowLogs] = useState(false);

  useEffect(() => {
    try {
      const byteCharacters = atob(result.pdfBase64);
      const byteNumbers = new Array(byteCharacters.length);
      for (let i = 0; i < byteCharacters.length; i++) {
        byteNumbers[i] = byteCharacters.charCodeAt(i);
      }
      const byteArray = new Uint8Array(byteNumbers);
      const blob = new Blob([byteArray], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      setBlobUrl(url);

      return () => {
        URL.revokeObjectURL(url);
      };
    } catch (e) {
      console.error('Error creating PDF blob URL:', e);
    }
  }, [result.pdfBase64]);

  const handleDownload = () => {
    if (!blobUrl) return;
    const a = document.createElement('a');
    a.href = blobUrl;
    a.download = result.fileName || 'converted_images.pdf';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  const handleOpenNewTab = () => {
    if (!blobUrl) return;
    window.open(blobUrl, '_blank');
  };

  return (
    <div id="pdf-preview-modal" className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-3 sm:p-6 overflow-y-auto">
      <div className="bg-white rounded-2xl shadow-2xl border border-slate-200 w-full max-w-4xl max-h-[92vh] flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-150">
        {/* Header */}
        <div className="px-5 py-4 border-b border-slate-200 flex items-center justify-between bg-slate-50/80">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-emerald-100 text-emerald-700 flex items-center justify-center">
              <CheckCircle2 className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-900 leading-tight">
                PDF Ready • {result.fileName}
              </h3>
              <p className="text-xs text-slate-500">
                Generated by Python 3.10 Engine
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              id="pdf-modal-download-btn"
              type="button"
              onClick={handleDownload}
              className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold shadow-xs hover:shadow transition-all cursor-pointer"
            >
              <Download className="w-3.5 h-3.5" />
              Download PDF ({formatBytes(result.sizeBytes)})
            </button>

            <button
              id="pdf-modal-open-btn"
              type="button"
              onClick={handleOpenNewTab}
              className="p-2 text-slate-500 hover:text-slate-800 hover:bg-slate-200/60 rounded-lg transition-colors cursor-pointer"
              title="Open in new tab"
            >
              <ExternalLink className="w-4 h-4" />
            </button>

            <button
              id="pdf-modal-close-btn"
              type="button"
              onClick={onClose}
              className="p-2 text-slate-400 hover:text-slate-700 hover:bg-slate-200/60 rounded-lg transition-colors cursor-pointer"
              title="Close preview"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Stats strip */}
        <div className="bg-slate-100/70 border-b border-slate-200 px-5 py-2.5 flex flex-wrap items-center gap-4 text-xs text-slate-600">
          <div className="flex items-center gap-1.5 font-medium">
            <Clock className="w-3.5 h-3.5 text-blue-600" />
            <span>Compiled in {result.durationMs}ms</span>
          </div>
          <div className="flex items-center gap-1.5 font-medium">
            <FileText className="w-3.5 h-3.5 text-indigo-600" />
            <span>{result.pageCount} {result.pageCount === 1 ? 'Page' : 'Pages'}</span>
          </div>
          <div className="flex items-center gap-1.5 font-medium">
            <HardDrive className="w-3.5 h-3.5 text-emerald-600" />
            <span>{formatBytes(result.sizeBytes)}</span>
          </div>
          <div className="flex items-center gap-1.5 font-medium text-slate-500">
            <Cpu className="w-3.5 h-3.5 text-amber-600" />
            <span>Python 3.10 Standard Library Engine</span>
          </div>
        </div>

        {/* PDF Viewer Body */}
        <div className="flex-1 bg-slate-200 min-h-[420px] max-h-[60vh] relative flex items-center justify-center p-2">
          {blobUrl ? (
            <iframe
              src={`${blobUrl}#toolbar=1`}
              title="PDF Preview"
              className="w-full h-full rounded-lg bg-white shadow-inner border border-slate-300"
            />
          ) : (
            <div className="text-center p-8 text-slate-500">
              <FileText className="w-12 h-12 mx-auto mb-2 text-slate-400 animate-pulse" />
              <p className="text-sm font-medium">Loading PDF document viewer...</p>
            </div>
          )}
        </div>

        {/* Diagnostics & Python Execution Log Dropdown */}
        <div className="px-5 py-3 border-t border-slate-200 bg-white">
          <button
            type="button"
            onClick={() => setShowLogs(!showLogs)}
            className="flex items-center justify-between w-full text-xs font-medium text-slate-600 hover:text-slate-900 cursor-pointer"
          >
            <span className="flex items-center gap-1.5">
              <Cpu className="w-3.5 h-3.5 text-slate-500" />
              Python Subprocess Execution Diagnostics
            </span>
            {showLogs ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
          </button>

          {showLogs && (
            <div className="mt-2.5 p-3 rounded-lg bg-slate-900 text-slate-100 font-mono text-[11px] overflow-x-auto max-h-36">
              <div className="text-emerald-400 mb-1">$ python3 scripts/converter.py --config config.json</div>
              <pre className="whitespace-pre-wrap">
                {JSON.stringify(
                  {
                    engine: 'Python 3.10.12 Standard Library (PDF 1.4 Object Model)',
                    status: 'success',
                    durationMs: result.durationMs,
                    sizeBytes: result.sizeBytes,
                    pageCount: result.pageCount,
                    ...result.stats,
                  },
                  null,
                  2
                )}
              </pre>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
